### ISSUE TITLE
Give credit

### ISSUE THREAD

**Issue by BearTS** [PPS2007/KdogOS#1]
Link the original repository link

**Comment by BearTS** [comment]
either in about or readme

**Comment by PPS2007** [comment]
Hello Bear.

**Comment by PPS2007** [comment]
Yes sure 😊. I will give credit.

**Comment by PPS2007** [comment]
By the way I can't message you on discord because we are in no server's in common.

**Comment by PPS2007** [comment]
Please send a friend request to me or send a server where you are.

**Comment by BearTS** [comment]
oh my Discord is Bear#3437 , what is your discord?
